param = {
  symbol: "GMTUSDT",
  collectedData: "trades",
  marketType: "FUTURES",
  fullDepth: {},
  depthSnapshot: undefined,
  depthSnapshotSended: false,
  updateDepth: [],
  depthUpdated: false,
  logData: false,
  binance: {},
  minDepthValue: 1,
  levelLength: 3,
  candle: {},
  newCandle: {
    o: 0,
    h: 0,
    l: 0,
    c: 0,
    lastBid: 0,
    lastAsk: 0,
    v: 0,
    mv: 0,
    q: 0,
    mq: 0,
    ticker: "",
    time: 0,
    bids: {},
    asks: {},
    numOfDepth: 0,
  },
};

module.exports.param = param;
